build:
    environment:
        php: '7.3'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

checks:
    php:
        code_rating: true

filter:
    excluded_paths:
        - config/*
        - tests/*
        - src/Generated/*
        - src/Pyz/*
