<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\Heidelpay;

interface HeidelpayConstants
{

    const PROVIDER_NAME = 'heidelpay';

    const PAYMENT_METHOD_SOFORT = self::PROVIDER_NAME . 'Sofort';
    const PAYMENT_METHOD_CREDIT_CARD_SECURE = self::PROVIDER_NAME . 'CreditCardSecure';
    const PAYMENT_METHOD_PAYPAL_AUTHORIZE = self::PROVIDER_NAME . 'PaypalAuthorize';
    const PAYMENT_METHOD_PAYPAL_DEBIT = self::PROVIDER_NAME . 'PaypalDebit';
    const PAYMENT_METHOD_IDEAL = self::PROVIDER_NAME . 'Ideal';

    const PAYMENT_OPTION_NEW_REGISTRATION = 'new-registration';
    const PAYMENT_OPTION_EXISTING_REGISTRATION = 'existing-registration';

    const PAYMENT_OPTION_EXISTING_REGISTRATION_POSITION = 0;
    const PAYMENT_OPTION_NEW_REGISTRATION_POSITION = 1;

    const TRANSACTION_TYPE_EXTERNAL_RESPONSE = 'external_response';
    const TRANSACTION_TYPE_DEBIT = 'debit';
    const TRANSACTION_TYPE_AUTHORIZE = 'authorize';
    const TRANSACTION_TYPE_AUTHORIZE_ON_REGISTRATION = 'authorize_on_registration';
    const TRANSACTION_TYPE_CAPTURE = 'capture';

    const EXTERNAL_RESPONSE_TRANSACTION_STATUS_OK = 'ACK';
    const CAPTURE_TRANSACTION_STATUS_OK = 'ACK';

    const CONFIG_HEIDELPAY_SECURITY_SENDER = 'CONFIG_HEIDELPAY_SECURITY_SENDER';
    const CONFIG_HEIDELPAY_USER_LOGIN = 'CONFIG_HEIDELPAY_USER_LOGIN';
    const CONFIG_HEIDELPAY_USER_PASSWORD = 'CONFIG_HEIDELPAY_USER_PASSWORD';
    const CONFIG_HEIDELPAY_TRANSACTION_CHANNEL = 'CONFIG_HEIDELPAY_TRANSACTION_CHANNEL';
    const CONFIG_HEIDELPAY_SANDBOX_REQUEST = 'CONFIG_HEIDELPAY_SANDBOX_REQUEST';
    const CONFIG_HEIDELPAY_APPLICATION_SECRET = 'CONFIG_HEIDELPAY_APPLICATION_SECRET';

    const CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_CC_3D_SECURE = 'CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_CC_3D_SECURE';
    const CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_PAYPAL = 'CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_PAYPAL';
    const CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_IDEAL = 'CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_IDEAL';
    const CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_SOFORT = 'CONFIG_HEIDELPAY_TRANSACTION_CHANNEL_SOFORT';

    const CONFIG_HEIDELPAY_LANGUAGE_CODE = 'CONFIG_HEIDELPAY_LANGUAGE_CODE';
    const CONFIG_HEIDELPAY_PAYMENT_RESPONSE_URL = 'CONFIG_HEIDELPAY_ZED_RESPONSE_URL';

    const CONFIG_YVES_URL = 'CONFIG_YVES_URL';

    const CONFIG_YVES_CHECKOUT_SUCCESS_URL = 'CONFIG_YVES_CHECKOUT_SUCCESS_URL';
    const CONFIG_YVES_CHECKOUT_PAYMENT_FAILED_URL = 'CONFIG_YVES_CHECKOUT_PAYMENT_FAILED_URL';
    const CONFIG_YVES_CHECKOUT_SUMMARY_STEP_URL = 'CONFIG_YVES_CHECKOUT_SUMMARY_STEP_URL';
    const CONFIG_YVES_CHECKOUT_PAYMENT_STEP_URL = 'CONFIG_YVES_CHECKOUT_PAYMENT_STEP_URL';
    const CONFIG_YVES_CHECKOUT_PAYMENT_STEP_PATH = 'CONFIG_YVES_CHECKOUT_PAYMENT_STEP_PATH';
    const CONFIG_YVES_CHECKOUT_ASYNC_RESPONSE_URL = 'CONFIG_YVES_CHECKOUT_ASYNC_RESPONSE_URL';
    const CONFIG_YVES_CHECKOUT_IDEAL_AUTHORIZE_URL = 'CONFIG_YVES_CHECKOUT_IDEAL_AUTHORIZE_URL';
    const CONFIG_YVES_CHECKOUT_PAYMENT_FRAME_CUSTOM_CSS_URL = 'CONFIG_YVES_CHECKOUT_PAYMENT_FRAME_CUSTOM_CSS_URL';
    const CONFIG_YVES_CHECKOUT_PAYMENT_FRAME_PREVENT_ASYNC_REDIRECT = 'CONFIG_YVES_CHECKOUT_PAYMENT_FRAME_PREVENT_ASYNC_REDIRECT';

}
